# Taps
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "bramstein/webfonttools"

# Brews
brew "zsh"
brew "python@2", link: true
brew "ansible"
brew "php@7.2", link: true
brew "composer"
brew "curl"
brew "exa"
brew "ffmpeg"
brew "flac"
brew "git"
brew "git-extras"
brew "git-lfs"
brew "git-secret"
brew "gnupg"
brew "mas"
brew "midnight-commander"
brew "mkcert"
brew "pwgen"
brew "rclone"
brew "sshuttle"
brew "tldr"
brew "unp"
brew "wget"
brew "wp-cli"
brew "youtube-dl"
brew "bramstein/webfonttools/sfnt2woff"
brew "bramstein/webfonttools/woff2"
brew "coreutils"
brew "automake"
brew "autoconf"
brew "openssl"
brew "libyaml"
brew "readline"
brew "libxslt"
brew "libtool"
brew "unixodbc"
brew "node@10"
brew "yarn"

# Casks
cask "1password"
cask "bartender"
cask "coconutbattery"
cask "colour-contrast-analyser"
cask "cyberduck"
cask "firefox", args: { language: "de" }
cask "firefox-developer-edition"
cask "firefox-nightly"
cask "flux"
cask "google-chrome"
cask "google-chrome-canary"
cask "imageoptim"
cask "iterm2"
cask "keybase"
cask "macdown"
cask "onedrive"
cask "opera"
cask "safari-technology-preview"
cask "osculator"
cask "reaper"
cask "sequel-pro"
cask "poedit"
cask "postman"
cask "qlmarkdown"
cask "qlvideo"
cask "skype"
cask "slack"
cask "spectacle"
cask "spotify"
cask "tripmode"
cask "viscosity"
cask "visual-studio-code"
cask "vlc"
cask "colorsnapper"
cask "notion"
cask "contexts"
cask "microsoft-office"
cask "microsoft-teams"

# Apps
mas "Agenda", id: 1287445660
mas "Battery Indicator", id: 1206020918
mas "PDF Letterhead Lite", id: 976548033
mas "Sim Daltonism", id: 693112260
mas "Telephone", id: 406825478

# Fonts
cask "font-barlow"
cask "font-gentium-basic"
cask "font-hack"
cask "font-inter"
cask "font-lato"
cask "font-merriweather"
cask "font-montserrat"
cask "font-open-sans"
cask "font-rajdhani"
cask "font-raleway"
cask "font-roboto"
cask "font-roboto-mono"
cask "font-source-sans-pro"
